package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"grpc/graph/model"
	"grpc/grpc_client"
	"grpc/models"
	"log"
)

// CreatePost is the resolver for the CreatePost field.
func (r *mutationResolver) CreatePost(ctx context.Context) (bool, error) {
	post := models.PrepareNewPost(model.Post{})

	res, err := grpc_client.CreatePost(":9090", post)
	if err != nil {
		log.Fatalf("Error while creating Post by graphQL ..... %v", err)
	} else {
		println("Creating Post by GraphQL successful .. message on GraphQl server, :))")
		println("Received response, ", res)
	}
	return res, nil
}

// UpdatePost is the resolver for the UpdatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, id string, input model.PostInput) (bool, error) {
	res, err := grpc_client.UpdatePost(":9090", id, input)

	if err != nil {
		log.Fatalf("Error while updating post....%v", err)
	} else {
		println("post updated successfully..., res = ", res)
	}
	return res, nil
}

// DeletePost is the resolver for the DeletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, postsID []string) ([]string, error) {
	res, err := grpc_client.DeletePost(":9090", postsID)

	if err != nil {
		log.Fatalf("Error while deleting post ..... %v", err)
	} else {
		println("Post delete successfully ..... wohoo!")
	}
	return res, err
}

// CreateCoupon is the resolver for the CreateCoupon field.
func (r *mutationResolver) CreateCoupon(ctx context.Context, couponCode *string) (*bool, error) {
	coupon := models.PrepareNewCoupon(model.Coupon{})

	res, err := grpc_client.CreateCoupon(":9090", coupon)
	if err != nil {
		log.Fatalf("Error while creating Coupon by graphQL ..... %v", err)
	} else {
		println("Creating Coupon by GraphQL successful .. message on GraphQl server, :))")
		println("Received response, ", res)
	}
	return &res, nil
}

// UpdateCoupon is the resolver for the UpdateCoupon field.
func (r *mutationResolver) UpdateCoupon(ctx context.Context, id string, input model.CouponInput) (bool, error) {
	res, err := grpc_client.UpdateCoupon(":9090", id, input)

	if err != nil {
		log.Fatalf("Error while Updating Coupon by graphQL ..... %v", err)
	} else {
		println("Updating Coupon by GraphQL successful .. message on GraphQl server, :))")
		println("Received response, ", res)
	}
	return res, nil
}

// DeleteCoupon is the resolver for the DeleteCoupon field.
func (r *mutationResolver) DeleteCoupon(ctx context.Context, coupons []string) ([]string, error) {
	res, err := grpc_client.DeleteCoupon(":9090", coupons)

	if err != nil {
		log.Fatalf("Error while deleting post ..... %v", err)
	} else {
		println("Post delete successfully ..... wohoo!")
	}
	return res, err
}

// GetPosts is the resolver for the GetPosts field.
func (r *queryResolver) GetPosts(ctx context.Context, ids []string) ([]*model.Post, error) {
	// lis := []string{"oBvaQhfFqVWVdDBgAhaER6", "MnwSHsuN9okaPEiSerDuA3"}
	posts := grpc_client.GetPosts(":9090", ids)

	ret := []*model.Post{}
	for i := 0; i < len(posts.Posts); i++ {
		p := model.Post{
			ID:        posts.Posts[i].Id,
			Title:     posts.Posts[i].Title,
			Content:   posts.Posts[i].Content,
			Author:    posts.Posts[i].Author,
			Comments:  posts.Posts[i].Comments,
			AuthorID:  posts.Posts[i].AuthorId,
			CreatedAt: posts.Posts[i].CreatedAt,
		}

		ret = append(ret, &p)
	}
	return ret, nil
}

// GetCoupons is the resolver for the GetCoupons field.
func (r *queryResolver) GetCoupons(ctx context.Context, codes []string) ([]*model.Coupon, error) {
	// lis := []string{"oBvaQhfFqVWVdDBgAhaER6", "MnwSHsuN9okaPEiSerDuA3"}
	Coupons := grpc_client.GetCoupon(":9090", codes)

	ret := []*model.Coupon{}
	for i := 0; i < len(Coupons.Coupons); i++ {
		c := model.Coupon{
			CouponCode: Coupons.Coupons[i].CouponCode,
			Amount:     Coupons.Coupons[i].Amount,
			CreatedAt:  Coupons.Coupons[i].CreatedAt,
		}
		ret = append(ret, &c)
	}
	return ret, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
